[package]
name = "folder_lock"
version = "1.0.0"
edition = "2025"

[dependencies]
age = "0.10"        
tar = "0.4"
flate2 = "1.0"
rpassword = "7.0"
clap = { version = "4.2", features = ["derive"] }
anyhow = "1.0"

